# KBO ELO System - Secure Production Deployment
# 환경변수 기반 보안 설정

services:
  # PostgreSQL Database with environment variables
  kbo-postgres:
    image: minkoosong/kbo-postgres-data:17.2
    container_name: kbo-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-kbo_elo_db}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?POSTGRES_PASSWORD is required}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - kbo_postgres_data:/var/lib/postgresql/data
    networks:
      - kbo-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-kbo_elo_db}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Main KBO ELO API
  kbo-api-main:
    image: minkoosong/kbo-api-main:latest
    container_name: kbo-api-8000
    ports:
      - "${MAIN_API_PORT:-8000}:8000"
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD}@kbo-postgres:5432/${POSTGRES_DB:-kbo_elo_db}
      PYTHONPATH: /app
      API_TITLE: "KBO ELO API"
      API_VERSION: "1.0.0"
    depends_on:
      kbo-postgres:
        condition: service_healthy
    networks:
      - kbo-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/system/db-status"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Live Rating API
  kbo-api-live:
    image: minkoosong/kbo-live-rating-api:latest
    container_name: kbo-api-8001
    ports:
      - "${LIVE_API_PORT:-8001}:8001"
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD}@kbo-postgres:5432/${POSTGRES_DB:-kbo_elo_db}
      PYTHONPATH: /app/kbo_elo_system
      WAIT_FOR_DB: "true"
      TEST_DB_CONNECTION: "true"
      API_TITLE: "KBO Live Rating API"
      API_VERSION: "2.0.0"
    depends_on:
      kbo-postgres:
        condition: service_healthy
    networks:
      - kbo-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend Application
  kbo-frontend:
    image: minkoosong/kbo-frontend:latest
    container_name: kbo-frontend
    ports:
      - "${FRONTEND_PORT:-3000}:80"
    environment:
      VITE_ELO_API_BASE_URL: /api
      VITE_LIVE_API_BASE_URL: /live-api
      VITE_API_BASE_URL: /api
      NGINX_HOST: localhost
      NGINX_PORT: 80
    depends_on:
      - kbo-api-main
      - kbo-api-live
    networks:
      - kbo-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Unified Scheduler
  kbo-unified-scheduler:
    image: minkoosong/kbo-unified-scheduler:v2
    container_name: kbo-unified-scheduler
    ports:
      - "${SCHEDULER_PORT:-8080}:8080"
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD}@kbo-postgres:5432/${POSTGRES_DB:-kbo_elo_db}
      PYTHONPATH: /app
      TZ: ${TIMEZONE:-Asia/Seoul}
      PYTHONIOENCODING: utf-8
    volumes:
      - kbo_scheduler_logs:/app/logs
      - kbo_scheduler_data:/app/data
      - kbo_scheduler_cache:/app/cache
    depends_on:
      kbo-postgres:
        condition: service_healthy
    networks:
      - kbo-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Nginx Reverse Proxy
  kbo-proxy:
    image: nginx:alpine
    container_name: kbo-nginx-proxy
    ports:
      - "${HTTP_PORT:-80}:80"
      - "${HTTPS_PORT:-443}:443"
    volumes:
      - ./nginx-production.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - kbo-frontend
      - kbo-api-main
      - kbo-api-live
    networks:
      - kbo-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  kbo_postgres_data:
    name: kbo_postgres_data
    driver: local
  kbo_scheduler_logs:
    name: kbo_scheduler_logs
    driver: local
  kbo_scheduler_data:
    name: kbo_scheduler_data
    driver: local
  kbo_scheduler_cache:
    name: kbo_scheduler_cache
    driver: local

networks:
  kbo-network:
    name: kbo-network
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16